logging:
  level: info

server:
  port: 3000

database:
  host: localhost
  port: 3306
  name: mt
  user: root
  password: b15dcpt082

security:
  cors:
    origins: '*'
    methods: '*'
    allowedHeaders: '*'
    exposedHeaders: '*'
    credentials: true
    maxAge: 1800
  jwt:
    issuer: moneytracker
    base64Secret: 'YXMyOTNPYXNrZEpIMTIzMWxqYXNrbGpLSlNBREgK'
    tokenValidityInSeconds: 3600

redis:
  host: localhost
  port: 6379
  user: default
  pass: b15dcpt082
  db: 1

openapi:
  path: api-docs
  title: Money Tracker API Docs
  description: The Money Tracker API Docs
  version: '1.0.0'

application:
